apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quarantine-deny-egress
spec:
  podSelector:
    matchLabels:
      security.devsecops/quarantine: "true"
  policyTypes:
  - Egress
  egress: []
