apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/erotonin/openstack-devsecops-voting.git
    targetRevision: staging
    path: k8s
    helm:
      valueFiles:
        - values-openstack.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
