
replicaCount: 1
images:
  vote:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
    tag: 2bf77f9e2ecbf9404a5aac5806686f74942b2d06
  result:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
    tag: 2bf77f9e2ecbf9404a5aac5806686f74942b2d06
  worker:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
    tag: 2bf77f9e2ecbf9404a5aac5806686f74942b2d06
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine
postgres:
  user: postgres
  password: password
  db: postgres
