kyverno:
  enabled: true
replicaCount: 1
service:
  type: ClusterIP
networkPolicy:
  enabled: true
ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote.local
    result: result.local
images:
  vote:
    repository: voting-app-vote
    tag: dev
    digest: ""
  result:
    repository: voting-app-result
    tag: dev
    digest: ""
  worker:
    repository: voting-app-worker
    tag: dev
    digest: ""
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine
appSecretName: voting-app-runtime
serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}
localDependencies:
  enabled: false
externalSecret:
  enabled: true
  storeName: aws-secrets-manager
  remoteKey: devsecops-voting/app-runtime
monitoring:
  enabled: false
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
resources:
  vote:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  result:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  worker:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
