kyverno:
  enabled: true
replicaCount: 1

service:
  # LoadBalancer exposes a public IP on AKS so DNS failover can point traffic here
  type: LoadBalancer

ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote-azure.example.com
    result: result-azure.example.com

images:
  vote:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-vote
    tag: 8dc69948077914955a8a0b78af4bedd1d8d3c4d2
    digest: sha256:8963781412356b7c7dbc35c6a064e638ff050da2795d0cc4f998911ecfcc4bc0
  result:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-result
    tag: 8dc69948077914955a8a0b78af4bedd1d8d3c4d2
    digest: sha256:3b843c88dcf4da9f825ff4456cbd0078783f1a2a0d0f9e118152ab0457d013f9
  worker:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-worker
    tag: 8dc69948077914955a8a0b78af4bedd1d8d3c4d2
    digest: sha256:1b2e5e27f0287e1f6d5fd4813890a4683bd065ffe4a28cd82c4da6fde832ee98
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: false
externalSecret:
  enabled: true
  storeName: azure-key-vault
  remoteKey: voting-app-runtime

monitoring:
  enabled: false
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  vote:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  result:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  worker:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi

