kyverno:
  enabled: false
replicaCount: 1

service:
  type: ClusterIP
services:
  vote:
    # Only vote needs a public endpoint for DNS failover and user traffic.
    type: LoadBalancer
  result:
    # Keep result private on Azure student subscriptions to avoid public IP quota.
    type: ClusterIP

ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote-azure.example.com
    result: result-azure.example.com

images:
  vote:
    repository: devsecopsvotingacrpgx92e.azurecr.io/voting-app-vote
    tag: 02713abbdd170890026d147ba31b1e9a3f6b09ac
    digest: sha256:56a9883bd01da3e481db43f270dd533f09ae3f324d7574ef5b3e70fb3d014654
  result:
    repository: devsecopsvotingacrpgx92e.azurecr.io/voting-app-result
    tag: 02713abbdd170890026d147ba31b1e9a3f6b09ac
    digest: sha256:ff6d709a67277d1c71d195673963baad6a80245305bab9b08b298030d3a0a37f
  worker:
    repository: devsecopsvotingacrpgx92e.azurecr.io/voting-app-worker
    tag: 02713abbdd170890026d147ba31b1e9a3f6b09ac
    digest: sha256:f3129dca2befba6fb02414431c582fe2a08a4fa6d3eaa261e6490ba8f105d462
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: false
  redis:
    enabled: true
externalSecret:
  enabled: true
  storeName: azure-key-vault
  remoteKey: voting-app-runtime

monitoring:
  enabled: false
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  vote:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  result:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  worker:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
