replicaCount: 1
service:
  type: NodePort
images:
  vote:
    repository: devsecopsvotingacrk1nhkh.azurecr.io/voting-app-vote
    tag: ce4b27645ec546d9cd82b03ade81f66c3885b917
  result:
    repository: devsecopsvotingacrk1nhkh.azurecr.io/voting-app-result
    tag: ce4b27645ec546d9cd82b03ade81f66c3885b917
  worker:
    repository: devsecopsvotingacrk1nhkh.azurecr.io/voting-app-worker
    tag: ce4b27645ec546d9cd82b03ade81f66c3885b917
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine
postgres:
  user: postgres
  password: password
  db: postgres
