replicaCount: 1

environment: openstack

service:
  type: ClusterIP

services:
  vote:
    type: ""
  result:
    type: ""

imagePullSecrets:
  - name: harbor-pull

images:
  vote:
    repository: harbor.openstack.local/voting/vote
    tag: dev
    digest: ""
  result:
    repository: harbor.openstack.local/voting/result
    tag: dev
    digest: ""
  worker:
    repository: harbor.openstack.local/voting/worker
    tag: dev
    digest: ""
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: true
  redis:
    enabled: true

externalSecret:
  enabled: false
  storeName: ""
  remoteKey: ""

networkPolicy:
  enabled: true

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    vote: vote.openstack.local
    result: result.openstack.local

podLabels: {}

storage:
  enabled: true
  createStorageClass: false
  className: cinder-csi
  size: 5Gi

monitoring:
  enabled: false
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m

otel:
  enabled: true
  endpoint: http://otel-collector:4317
  insecure: "true"

kyverno:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

resources:
  vote:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  result:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  worker:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  redis:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  db:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
