replicaCount: 1

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote.local
    result: result.local

images:
  vote:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
    tag: f2e8604c9ac4a7e3c708ae1d16682cc4b9db2994
  result:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
    tag: f2e8604c9ac4a7e3c708ae1d16682cc4b9db2994
  worker:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
    tag: f2e8604c9ac4a7e3c708ae1d16682cc4b9db2994
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: true
externalSecret:
  enabled: false
  storeName: aws-secrets-manager
  remoteKey: devsecops-voting/app-runtime

resources:
  vote:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  result:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  worker:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
