replicaCount: 3

service:
  type: LoadBalancer

ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote.example.com
    result: result.example.com

images:
  vote:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
    tag: e164025b90fccd645e2aa2853d485d0023019103
    digest: sha256:5713af8d425b51ed0e1c044fa2b8db5f981581428c75fe4c0912fae904c71f0b
  result:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
    tag: e164025b90fccd645e2aa2853d485d0023019103
    digest: sha256:acbb6f181ca97025edb9a1daacd3d6c18a8a5993fc2783e5df8319097487c253
  worker:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
    tag: e164025b90fccd645e2aa2853d485d0023019103
    digest: sha256:45206dcd2a8fb3500b641448fa200c1d2ccd5771d6dd252b9953506cc17a1851
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: false
externalSecret:
  enabled: true
  storeName: aws-secrets-manager
  remoteKey: devsecops-voting/app-runtime

monitoring:
  enabled: true
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  vote:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  result:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  worker:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

kyverno:
  enabled: true
