replicaCount: 3

service:
  type: LoadBalancer

ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote.example.com
    result: result.example.com

images:
  vote:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
    tag: 085cbf139a8cd731a6c0809793ae7878a6017ca7
    digest: sha256:2639b7b7ce97f43c7a4362d330c25d1accf76233a30ac2effbd896f41aac6143
  result:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
    tag: 085cbf139a8cd731a6c0809793ae7878a6017ca7
    digest: sha256:e6fa6ea5435a58662f59ab3c4fdbc0988be01a053d847b733de72599e19ac67d
  worker:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
    tag: 085cbf139a8cd731a6c0809793ae7878a6017ca7
    digest: sha256:9423a35b9d149480c0375910468359cede9d6507626dc7902c1d387b077e2551
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: false
externalSecret:
  enabled: true
  storeName: aws-secrets-manager
  remoteKey: devsecops-voting/app-runtime

monitoring:
  enabled: true
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  vote:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  result:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  worker:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
