replicaCount: 3

service:
  type: LoadBalancer

ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote.example.com
    result: result.example.com

images:
  vote:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
    tag: 83a7747b71b5efe6d9eeb998776d9e896e89ab15
    digest: sha256:f9f43f2f3a059cfd28a81dfa82e1902866e9e62aa84a6b08a866b7392e5aa01e
  result:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
    tag: 83a7747b71b5efe6d9eeb998776d9e896e89ab15
    digest: sha256:9831b4e0224564a2bca5c78478b5da1ccac83118f0ac8755bcdfe091863971cd
  worker:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
    tag: 83a7747b71b5efe6d9eeb998776d9e896e89ab15
    digest: sha256:7e48a83c68bc68a2e5dbe3747bdc5649684bfaac548287e8c7355d1fc63cbd26
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: false
externalSecret:
  enabled: true
  storeName: aws-secrets-manager
  remoteKey: devsecops-voting/app-runtime

monitoring:
  enabled: true
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  vote:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  result:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  worker:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

kyverno:
  enabled: true
