{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: voting-app-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.storeName }}
  target:
    name: {{ .Values.appSecretName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.remoteKey }}
{{- else if .Values.localDependencies.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecretName }}
type: Opaque
stringData:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_SSL: "false"
  DB_HOST: db
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: postgres
  DB_SSL: "false"
  DB_SSL_MODE: Disable
  DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
  COOKIE_SECURE: "false"
  APP_SIGNING_KEY: devsecops-voting-local-key
{{- end }}
