apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: {{ .Values.images.result.repository }}:{{ .Values.images.result.tag }}
        ports:
        - containerPort: 4000
          name: result
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: result
