apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.vote.name }}
  annotations:
{{ toYaml .Values.serviceAccounts.vote.annotations | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.result.name }}
  annotations:
{{ toYaml .Values.serviceAccounts.result.annotations | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.worker.name }}
  annotations:
{{ toYaml .Values.serviceAccounts.worker.annotations | indent 4 }}
