apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: {{ .Values.images.vote.repository }}:{{ .Values.images.vote.tag }}
        ports:
        - containerPort: 80
          name: vote
---
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: vote
