name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'k8s/values-*.yaml'

permissions:
  id-token: write
  contents: write

jobs:
  owasp-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'DevSecOps-Voting-App'
        path: '.'
        format: 'HTML'
        args: >
          --failOnCVSS 7
          --enableRetired
          --suppression suppression.xml

  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.projectKey=devsecops-voting
          -Dsonar.projectName=devsecops-voting
          -Dsonar.sources=vote,result
          -Dsonar.exclusions=**/node_modules/**,**/views/**
          -Dsonar.c.file.suffixes=-
          -Dsonar.cpp.file.suffixes=-
          -Dsonar.objc.file.suffixes=-
          -Dsonar.python.version=3.11
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Install SonarScanner for .NET
      run: dotnet tool install --global dotnet-sonarscanner
    - name: SonarQube Scan (Worker / C#)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        dotnet sonarscanner begin /k:"Worker-App" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        dotnet build ./worker/Worker.csproj
        dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  build-and-push:
    runs-on: ubuntu-latest
    needs: [owasp-scan, sonarqube-scan]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Login to Azure ACR
      run: az acr login --name devsecopsvotingacrk1nhkh
    - name: Build VOTE
      run: docker build -t voting-app-vote:${{ github.sha }} ./vote
    - name: Scan VOTE with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'voting-app-vote:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
    - name: Build RESULT
      run: docker build -t voting-app-result:${{ github.sha }} ./result
    - name: Scan RESULT with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'voting-app-result:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
    - name: Build WORKER
      run: docker build -t voting-app-worker:${{ github.sha }} ./worker
    - name: Scan WORKER with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'voting-app-worker:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
    - name: Push to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker tag voting-app-vote:$IMAGE_TAG $ECR_REGISTRY/voting-app-vote:$IMAGE_TAG
        docker push $ECR_REGISTRY/voting-app-vote:$IMAGE_TAG
        docker tag voting-app-result:$IMAGE_TAG $ECR_REGISTRY/voting-app-result:$IMAGE_TAG
        docker push $ECR_REGISTRY/voting-app-result:$IMAGE_TAG
        docker tag voting-app-worker:$IMAGE_TAG $ECR_REGISTRY/voting-app-worker:$IMAGE_TAG
        docker push $ECR_REGISTRY/voting-app-worker:$IMAGE_TAG
    - name: Push to ACR
      env:
        ACR_REGISTRY: devsecopsvotingacrk1nhkh.azurecr.io
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker tag voting-app-vote:$IMAGE_TAG $ACR_REGISTRY/voting-app-vote:$IMAGE_TAG
        docker push $ACR_REGISTRY/voting-app-vote:$IMAGE_TAG
        docker tag voting-app-result:$IMAGE_TAG $ACR_REGISTRY/voting-app-result:$IMAGE_TAG
        docker push $ACR_REGISTRY/voting-app-result:$IMAGE_TAG
        docker tag voting-app-worker:$IMAGE_TAG $ACR_REGISTRY/voting-app-worker:$IMAGE_TAG
        docker push $ACR_REGISTRY/voting-app-worker:$IMAGE_TAG
    - name: Update Helm values
      run: |
        yq e -i '.images.vote.tag = "${{ github.sha }}"' k8s/values-dev.yaml
        yq e -i '.images.result.tag = "${{ github.sha }}"' k8s/values-dev.yaml
        yq e -i '.images.worker.tag = "${{ github.sha }}"' k8s/values-dev.yaml
        yq e -i '.images.vote.tag = "${{ github.sha }}"' k8s/values-prod.yaml
        yq e -i '.images.result.tag = "${{ github.sha }}"' k8s/values-prod.yaml
        yq e -i '.images.worker.tag = "${{ github.sha }}"' k8s/values-prod.yaml
        yq e -i '.images.vote.tag = "${{ github.sha }}"' k8s/values-azure.yaml
        yq e -i '.images.result.tag = "${{ github.sha }}"' k8s/values-azure.yaml
        yq e -i '.images.worker.tag = "${{ github.sha }}"' k8s/values-azure.yaml
        git config user.name "erotonin"
        git config user.email "erotonin@users.noreply.github.com"
        git add k8s/values-dev.yaml k8s/values-prod.yaml k8s/values-azure.yaml
        git commit -m "Update image tags to ${{ github.sha }} for Dev, Prod & Azure"
        git push
